# Generated by Django 3.2.8 on 2021-10-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('origin_string', models.CharField(max_length=50)),
                ('destination_string', models.CharField(max_length=50)),
                ('data', models.JSONField()),
            ],
        ),
    ]
