# Generated by Django 3.2.8 on 2021-10-21 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
